# @Author: German Cano Quiveu <germancq>
# @Date:   2018-11-13T21:37:15+01:00
# @Email:  germancq@dte.us.es
# @Last modified by:   germancq
# @Last modified time: 2018-11-19T15:14:34+01:00


VERILOG_SOURCES = ../../spi_master.sv \
				  ../../../misc/counter.sv \
				  ../../../misc/register.sv \
				  ../../../misc/shift_register.sv 
				  
TOPLEVEL=spi_master
MODULE=spi_master_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim


